-- +goose Up
ALTER TABLE feeds
ADD COLUMN IF NOT EXISTS last_fetched_at TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

-- +goose Down
ALTER TABLE feeds
DROP COLUMN IF EXISTS last_fetched_at,
DROP COLUMN IF EXISTS updated_at,
DROP COLUMN IF EXISTS created_at;
